#
# Makefile to build cm2mlb.
#
# by: Joshua Dunfield
#
# Use this, unless you enjoy copying and pasting instructions from
#  comments inside source files.
#
# Requires that $SMLNJ_HOME be set appropriately.

all : cm2mlb

cm2mlb : 
	./build-cm2mlb
